modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="movementplus"
version="1.0.0"
displayName="Movement+"
authors="NegativeStudios"
description="Adds the Lashing Potato grappling tool from the 24w14potato snapshot to Minecraft 1.20.1."

[[dependencies.movementplus]]
modId="forge"
mandatory=true
versionRange="[47.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.movementplus]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
